import type { Metadata } from 'next'
import './globals.css'
import { Providers } from './providers'
import Navigater from './components/Navbar'
import ShoppingCartModal from './components/ShoppingCartModal'

export const metadata: Metadata = {
  title: 'Sanity Eccomerce App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en' className='dark'>
      <body>
        <Providers>
          <Navigater />
          <ShoppingCartModal />
          {children}
        </Providers>
      </body>
    </html>
  )
}
